---
- name: Package prerequisites
  apt: name='{{ item }}' state=present
  with_items:
  - make
  - gcc
  - curl
  - perl-doc
  - libmodule-build-perl
  tags: [ perlbrew, prereq ]
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: 'Make PERLBREW_ROOT'
  file: path='{{ perlbrew_root }}' owner='{{ user }}' mode=0755 state=directory

- name: Download perlbrew install script
  get_url: url=https://gugod.github.io/App-perlbrew/perlbrew dest=/tmp/perlbrew-installer-{{ user }} mode=0755
  tags: [ perlbrew, install ]

- name: Install perlbrew
  shell: PERLBREW_ROOT='{{ perlbrew_root }}' /usr/bin/perl /tmp/perlbrew-installer-{{ user }} self-install creates='{{ perlbrew_root }}/bin/perlbrew'
  tags: [ perlbrew, install ]

- name: Install patchperl
  shell: PERLBREW_ROOT='{{ perlbrew_root }}' /usr/bin/perl /tmp/perlbrew-installer-{{ user }} -f -q install-patchperl creates='{{ perlbrew_root }}/bin/patchperl'
  tags: [ perlbrew, install ]

- name: Init ~/.bashrc
  sudo: yes
  sudo_user: '{{ user }}'
  lineinfile: dest='{{ item.dest }}' line='{{ item.line }}'
  with_items:
  - { dest: '~/.bashrc', line: 'export PERLBREW_ROOT={{ perlbrew_root }}' }
  - { dest: '~/.bashrc', line: 'source {{ perlbrew_root }}/etc/bashrc' }
  tags: [ perlbrew, config ]

- name: Install Perl
  sudo: yes
  sudo_user: '{{ user }}'
  shell: PERLBREW_ROOT='{{ perlbrew_root }}' perlbrew install --verbose {{ perl_version }} creates='{{ perlbrew_root }}/perls/{{ perl_version }}'
  tags: [ perlbrew, install ]

- name: Install cpanm
  sudo: yes
  sudo_user: '{{ user }}'
  shell: perlbrew install-cpanm creates='{{ perlbrew_root }}/bin/cpanm'
  tags: [ perlbrew, install ]

- name: Use Perl {{ perl_version }}
  sudo: yes
  sudo_user: '{{ user }}'
  shell: PERLBREW_BASHRC_VERSION=1 perlbrew switch {{ perl_version }}
  tags: [ perlbrew, install ]
