---
- name: Package prerequisites
  apt: name='{{ item }}' state=present
  with_items:
  - make
  - gcc
  - curl
  - perl-doc
  - libmodule-build-perl
  - perlbrew
  tags: [ perlbrew, prereq ]

- name: 'Make PERLBREW_ROOT'
  file: path='{{ perlbrew_root }}' owner='{{ user }}' mode=0755 state=directory

- name: Init for {{ user }}
  sudo: yes
  sudo_user: '{{ user }}'
  shell: PERLBREW_ROOT='{{ perlbrew_root }}' perlbrew init creates='{{ perlbrew_root }}'
  tags: [ perlbrew, config ]

- name: Init /home/{{ user }}/.bashrc
  sudo: yes
  sudo_user: '{{ user }}'
  lineinfile: dest='{{ item.dest }}' line='{{ item.line }}'
  with_items:
  - { dest: '/home/{{ user }}/.bashrc', line: 'export PERLBREW_ROOT={{ perlbrew_root }}' }
  - { dest: '/home/{{ user }}/.bashrc', line: 'source {{ perlbrew_root }}/etc/bashrc' }
  tags: [ perlbrew, config ]

- name: Install Perl
  sudo: yes
  sudo_user: '{{ user }}'
  shell: PERLBREW_ROOT='{{ perlbrew_root }}' perlbrew install --verbose {{ perl_version }} creates='{{ perlbrew_root }}/perls/{{ perl_version }}'
  tags: [ perlbrew, install ]

- name: Install cpanm
  sudo: yes
  sudo_user: '{{ user }}'
  shell: perlbrew install-cpanm creates='{{ perlbrew_root }}/bin/cpanm'
  tags: [ perlbrew, install ]

- name: Use Perl {{ perl_version }}
  sudo: yes
  sudo_user: '{{ user }}'
  shell: PERLBREW_BASHRC_VERSION=1 perlbrew switch {{ perl_version }}
  tags: [ perlbrew, install ]
