- name: Package prerequisites
  apt: name='{{ item }}' state=present
  with_items:
  - curl
  - gcc
  - make
  - perl-doc
  - libmodule-build-perl
  - perlbrew
  tags: [ perlbrew, prereq ]
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- yum: name='{{ item }}' state=present
  with_items:
  - curl
  - gcc
  - make
  - bzip2
  - perl
  - libselinux-python
  when: ansible_distribution == 'CentOS' 

